server:
  port: 8090
xrpc:
  providers: http://127.0.0.1:8081,http://127.0.0.1:8082,http://127.0.0.1:8083
  zkServers: localhost:2181
  zkRoot: xrpc
app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
logging:
  level:
    root: info
    com.yuanstack.xrpc: debug