server:
  port: 8091
xrpc:
  zk:
    server: localhost:2181
    root: xrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 33 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000
xregistry:
  enabled: true
  servers: http://localhost:8484

logging:
  level:
    root: info
    com.yuanstack.xrpc: debug