### 根据用户ID获取用户信息

POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.yuanstack.xrpc.demo.api.service.UserService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [
    101
  ]
}

### 根据用户ID获取用户信息

POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.yuanstack.xrpc.demo.api.service.UserService",
  "methodSign": "findById@2_java.lang.Integer_java.lang.String",
  "args": [
    101,
    "Stack"
  ]
}

### 根据订单ID获取订单信息

POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.yuanstack.xrpc.demo.api.service.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [
    101
  ]
}

### mock

POST http://localhost:8081/
Content-Type: application/json

{
  "service": "com.yuanstack.xrpc.demo.api.service.UserService",
  "methodSign": "toString",
  "args": [
  ]
}

