server:
  port: 8081
xrpc:
  zk:
    server: localhost:2181
    root: xrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 300
logging:
  level:
    root: debug
    com.yuanstack.xrpc: debug

app:
  id: app1
apollo:
  cacheDir: /opt/data/                       #配置本地配置缓存目录
  cluster: default                           #指定使用哪个集群的配置
  meta: http://localhost:8080           #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: app1                  #设置 Namespace
    eagerLoad:
      enabled: false