server:
  port: 8081
xrpc:
  zk:
    server: localhost:2181
    root: xrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
logging:
  level:
    root: info
    com.yuanstack.xrpc: debug